"""empty message

Revision ID: 49379341a0ad
Revises: 02675774f0d8
Create Date: 2019-12-19 19:19:18.331376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49379341a0ad'
down_revision = '02675774f0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
